name: Branch Environment Demo

on:
  workflow_dispatch:
  push:
  pull_request: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' && 'production' || github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/development' && 'development' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "Using environment with var ${{ vars.ENV_VAR_1 }}."
        # placeholder for demo