name: Branch Environment Demo

on:
  workflow_dispatch:
  push:
  pull_request: 
    branches:
      - main

jobs:

  deploy:
    environment: production
    runs-on: ubuntu-latest
    # Expose step outputs as job outputs
    outputs:
      ecr: ${{ steps.build-ecr-string.outputs.ecr }}

    steps:
    - name: Build ECR string
      id: build-ecr-string
      shell: bash
      run: |
        ECR_STRING="${{ secrets.ECR_SECRET }}.dkr.ecr.eu-central-1.amazonaws.com/ecr-name"
        echo "::add-mask::$ECR_STRING"
        echo "ecr=$ECR_STRING" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - run: echo ${{needs.deploy.outputs.ecr}}

