name: Branch Environment Demo

on:
  workflow_dispatch:
  push:
  pull_request: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' && 'production' || github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/development' && 'development' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "Using environment with var ${{ vars.ENV_VAR_1 }}."

      - name: Build ECR string
        id: build-ecr-string
        run: echo "::set-output name=ecr_string::${{ env.ECR_SECRET }}.dkr.ecr.eu-central-1.amazonaws.com/ecr-name"
        env:
          ECR_SECRET: ${{ secrets.ECR_SECRET }}

  container-test-job:
    needs: deploy
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.deploy.outputs.ecr_string }}

    steps:
      - run: echo "Running tests in container"